name: Gunluk Bulten Cekici
on:
  workflow_dispatch:

permissions:
  contents: write  # BOTA YAZMA İZNİ VERİYORUZ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4
      - name: Run Scraper
        run: python SirionX.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add maclar.csv || echo "Dosya yok"
          git commit -m "Bulten guncellendi" || echo "Degisiklik yok"
          git push
