name: Gunluk Bulten Cekici
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Paketleri Kur
        run: pip install pandas requests beautifulsoup4
      - name: Bülteni Çek
        run: python SirionX.py
      - name: Değişiklikleri Kaydet
        run: |
          git config --global user.name "SirionX-Bot"
          git config --global user.email "bot@sirionx.com"
          git add maclar.csv || echo "Dosya yok"
          git commit -m "Bulten guncellendi" || echo "Degisiklik yok"
          git push
