name: Gunluk Bulten Cekici
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git push yetkisi için kritik!
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Paketleri Kur
        run: pip install pandas requests beautifulsoup4

      - name: Bülteni Çek
        run: python SirionX.py

      - name: Değişiklikleri Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Mevcut değişiklikleri çekip birleştirmeye çalış (Sorunu çözer)
          git pull origin main --rebase --autostash
          
          git add maclar.csv
          git commit -m "Bulten guncellendi" || echo "Degisiklik yok"
          git push origin main
